---
- name: "Include vars"
  ansible.builtin.include_vars: "../vars/{{ env }}/ah_repository.yml"
  tags:
    - "repos"

- name: "Import ah_configuration role"
  ansible.builtin.import_role:
    name: "redhat_cop.ah_configuration.repository"
  tags:
    - "repos"
...
